export const SHOP_ACTION_TYPES = {
  FETCH_SECTIONS_FROM_FIRESTORE_START: "FETCH_SECTIONS_FROM_FIRESTORE_START",

  FETCH_SECTIONS_FROM_FIRESTORE_SUCCESS:
    "FETCH_SECTIONS_FROM_FIRESTORE_SUCCESS",

  FETCH_SECTIONS_FROM_FIRESTORE_FAILURE:
    "FETCH_SECTIONS_FROM_FIRESTORE_FAILURE",
};
